### ISSUE TITLE
Fast track layout and menu broken [JIRA: PMT-100]

### ISSUE THREAD

**Issue by roooms** [basho/basho_docs#1547] opened 2015-03-05 11:13 UTC
http://docs.basho.com/riak/latest/tutorials/fast-track/ 
* menu and page structure is broken
* the nav on the left seems to append urls together incorrectly, causing 404’s

**Comment by kesslerm** [comment] 2015-03-05 11:29
The latest working version of this belongs to Riak 1.3.2. Is there a left-over file in the 'latest' section on the doc-server?

This one works as intended: http://docs.basho.com/riak/1.3.2/tutorials/fast-track/

This one shows a 404 error, as intended: http://docs.basho.com/riak/2.0.5/tutorials/fast-track/

**Comment by roooms** [comment] 2015-03-05 11:39
The link to this URL is available in the FAQs at http://docs.basho.com/riak/latest/community/faqs/basics/#what-is-riak

**Comment by TheOnlyRew** [comment] 2015-03-19 21:24
With #1549 merged, can this issue be closed?

**Comment by laurenrother** [comment] 2015-04-28 17:28
Please feel free to reopen this issue if the PR above did not satisfactorily resolve the issue.

**Closed** 2015-04-28 17:28 UTC
Labels: JIRA: To Do
