### ISSUE TITLE
The Rolling Downgrades section needs to be updated to include downgrading from Riak 2.0/2.1

### ISSUE THREAD

**Issue by dannylauca** [basho/basho_docs#1732] opened 2015-06-24 15:44 UTC
The section, http://docs.basho.com/riak/latest/ops/upgrading/rolling-downgrades, currently only discusses downgrade from Riak 1.4.  See the following ticket for a CentOS example which shows how to downgrade from 2.0 to 1.4: https://basho.zendesk.com/agent/tickets/11204

**Comment by dannylauca** [comment] 2015-06-24 15:56
The following are the steps for downgrading from Riak 2.0 to 1.4(.8) on CentOS:

Stop Riak
$ sudo riak stop

Backup the data and configuration files directories
$ sudo tar cvf ~/riak_backup.tar.gz /var/lib/riak /etc/riak

Downgrade to Riak 1.4.8 EE
$ sudo yum downgrade http://s3.amazonaws.com/private.downloads.basho.com/riak_ee/20b089/1.4.8/rhel/6/riak-ee-1.4.8-1.el6.x86_64.rpm

Update the app.config and vm.args files in the /etc/riak directory, if necessary, or restore the configuration files from the previous 1.4.8 installation. For example, the setting of the nodename parameter in the riak.conf file should be the same as the setting of the -name parameter in the vm.args file. Also, the setting of the cluster_mgr parameter in the advanced.config file should be the same as the setting of the cluster_mgr parameter in the app.config file.

If you updated the riak.conf and/or advanced.config files in the 2.0 installation, these files will be preserved in the /etc/riak directory and renamed with a .rpmsave extension after the downgrade in the previous step.

Start Riak
$ sudo riak start

Verify the version of Riak that is now running
$ riak version

Wait for the riak_kv service to start
$ sudo riak-admin wait-for-service riak_kv <name-and-IP-address-of-node>

Wait for hinted handoff transfers to complete
$ sudo riak-admin transfers

Repeat procedure for each node.

**Comment by Basho-JIRA** [comment] 2017-01-18 15:27
Duplicate of https://bashoeng.atlassian.net/browse/DOC-111 

***[posted via JIRA by Lauren Rother]***

**Closed by Basho-JIRA** 2017-01-18 15:27 UTC
Labels: JIRA: Closed

**Comment by Basho-JIRA** [comment] 2017-02-03 15:51
https://github.com/basho/basho_docs/pull/2420 

***[posted via JIRA by Lauren Rother]***
