### ISSUE TITLE
Global vs per-backend settings

### ISSUE THREAD

**Issue by lukebakken** [basho/basho_docs#1138] opened 2014-06-12 15:37 UTC
The global backend settings (like Bitcask's `merge_window` and `io_mode`) should be clearly documented as such as opposed to per-backend settings (like `data_root`).

http://docs.basho.com/riak/latest/ops/advanced/backends/multi/

**Comment by kesslerm** [comment] 2015-03-18 12:23
Duplicate of #1548

**Closed by kesslerm** 2015-03-18 12:23 UTC
Labels: 2.0, duplicate, enhancement
